/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "defs/E2SM-RC-R003-v03.00.asn1"
 * 	`asn1c -fcompound-names -findirect-choice -fincludes-quoted -fno-include-deps -gen-PER -no-gen-OER -no-gen-example`
 */

#include "AdditionalSupportedFormat-UEGroupControl.h"

asn_TYPE_member_t asn_MBR_AdditionalSupportedFormat_UEGroupControl_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AdditionalSupportedFormat_UEGroupControl, ric_ControlHeaderFormat_Type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Format_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-ControlHeaderFormat-Type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AdditionalSupportedFormat_UEGroupControl, ric_ControlMessageFormat_Type),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Format_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-ControlMessageFormat-Type"
		},
};
static const ber_tlv_tag_t asn_DEF_AdditionalSupportedFormat_UEGroupControl_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AdditionalSupportedFormat_UEGroupControl_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ric-ControlHeaderFormat-Type */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ric-ControlMessageFormat-Type */
};
asn_SEQUENCE_specifics_t asn_SPC_AdditionalSupportedFormat_UEGroupControl_specs_1 = {
	sizeof(struct AdditionalSupportedFormat_UEGroupControl),
	offsetof(struct AdditionalSupportedFormat_UEGroupControl, _asn_ctx),
	asn_MAP_AdditionalSupportedFormat_UEGroupControl_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AdditionalSupportedFormat_UEGroupControl = {
	"AdditionalSupportedFormat-UEGroupControl",
	"AdditionalSupportedFormat-UEGroupControl",
	&asn_OP_SEQUENCE,
	asn_DEF_AdditionalSupportedFormat_UEGroupControl_tags_1,
	sizeof(asn_DEF_AdditionalSupportedFormat_UEGroupControl_tags_1)
		/sizeof(asn_DEF_AdditionalSupportedFormat_UEGroupControl_tags_1[0]), /* 1 */
	asn_DEF_AdditionalSupportedFormat_UEGroupControl_tags_1,	/* Same as above */
	sizeof(asn_DEF_AdditionalSupportedFormat_UEGroupControl_tags_1)
		/sizeof(asn_DEF_AdditionalSupportedFormat_UEGroupControl_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_AdditionalSupportedFormat_UEGroupControl_1,
	2,	/* Elements count */
	&asn_SPC_AdditionalSupportedFormat_UEGroupControl_specs_1	/* Additional specs */
};

