/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "defs/E2SM-RC-R003-v03.00.asn1"
 * 	`asn1c -fcompound-names -findirect-choice -fincludes-quoted -fno-include-deps -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_Associated_UE_Info_Item_H_
#define	_Associated_UE_Info_Item_H_


#include "asn_application.h"

/* Including external dependencies */
#include "UE-Filter-ID.h"
#include "LogicalOR.h"
#include "constr_CHOICE.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Associated_UE_Info_Item__ueType_PR {
	Associated_UE_Info_Item__ueType_PR_NOTHING,	/* No components present */
	Associated_UE_Info_Item__ueType_PR_ueType_Choice_Individual,
	Associated_UE_Info_Item__ueType_PR_ueType_Choice_Group
	/* Extensions may appear below */
	
} Associated_UE_Info_Item__ueType_PR;

/* Forward declarations */
struct EventTrigger_UE_Info_Item_Choice_Individual;
struct EventTrigger_UE_Info_Item_Choice_Group;

/* Associated-UE-Info-Item */
typedef struct Associated_UE_Info_Item {
	UE_Filter_ID_t	 ueFilterID;
	struct Associated_UE_Info_Item__ueType {
		Associated_UE_Info_Item__ueType_PR present;
		union Associated_UE_Info_Item__ueType_u {
			struct EventTrigger_UE_Info_Item_Choice_Individual	*ueType_Choice_Individual;
			struct EventTrigger_UE_Info_Item_Choice_Group	*ueType_Choice_Group;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ueType;
	LogicalOR_t	*logicalOR;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Associated_UE_Info_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Associated_UE_Info_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_Associated_UE_Info_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_Associated_UE_Info_Item_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _Associated_UE_Info_Item_H_ */
#include "asn_internal.h"
