/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "defs/E2SM-RC-R003-v03.00.asn1"
 * 	`asn1c -fcompound-names -findirect-choice -fincludes-quoted -fno-include-deps -gen-PER -no-gen-OER -no-gen-example`
 */

#include "E2SM-RC-ControlHeader-Format3.h"

asn_TYPE_member_t asn_MBR_E2SM_RC_ControlHeader_Format3_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_ControlHeader_Format3, ue_Group_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_Group_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ue-Group-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_ControlHeader_Format3, ue_Group_Definition),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_Group_Definition,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ue-Group-Definition"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_ControlHeader_Format3, ric_Style_Type),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Style_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-Style-Type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_ControlHeader_Format3, ric_ControlAction_ID),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_ControlAction_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-ControlAction-ID"
		},
};
static const ber_tlv_tag_t asn_DEF_E2SM_RC_ControlHeader_Format3_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E2SM_RC_ControlHeader_Format3_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ue-Group-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ue-Group-Definition */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ric-Style-Type */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* ric-ControlAction-ID */
};
asn_SEQUENCE_specifics_t asn_SPC_E2SM_RC_ControlHeader_Format3_specs_1 = {
	sizeof(struct E2SM_RC_ControlHeader_Format3),
	offsetof(struct E2SM_RC_ControlHeader_Format3, _asn_ctx),
	asn_MAP_E2SM_RC_ControlHeader_Format3_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E2SM_RC_ControlHeader_Format3 = {
	"E2SM-RC-ControlHeader-Format3",
	"E2SM-RC-ControlHeader-Format3",
	&asn_OP_SEQUENCE,
	asn_DEF_E2SM_RC_ControlHeader_Format3_tags_1,
	sizeof(asn_DEF_E2SM_RC_ControlHeader_Format3_tags_1)
		/sizeof(asn_DEF_E2SM_RC_ControlHeader_Format3_tags_1[0]), /* 1 */
	asn_DEF_E2SM_RC_ControlHeader_Format3_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2SM_RC_ControlHeader_Format3_tags_1)
		/sizeof(asn_DEF_E2SM_RC_ControlHeader_Format3_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E2SM_RC_ControlHeader_Format3_1,
	4,	/* Elements count */
	&asn_SPC_E2SM_RC_ControlHeader_Format3_specs_1	/* Additional specs */
};

