/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "defs/E2SM-RC-R003-v03.00.asn1"
 * 	`asn1c -fcompound-names -findirect-choice -fincludes-quoted -fno-include-deps -gen-PER -no-gen-OER -no-gen-example`
 */

#include "E2SM-RC-ControlMessage-Format3.h"

#include "E2SM-RC-EntityFilter.h"
#include "EntityAgnostic-ranP-ControlParameters.h"
static int
memb_listOfEntityFilters_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size <= 255)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_entityAgnosticControlRanP_List_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size <= 65535)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_listOfEntityFilters_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (SIZE(0..255)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_entityAgnosticControlRanP_List_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_listOfEntityFilters_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (SIZE(0..255)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_entityAgnosticControlRanP_List_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_listOfEntityFilters_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2SM_RC_EntityFilter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_listOfEntityFilters_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfEntityFilters_specs_2 = {
	sizeof(struct E2SM_RC_ControlMessage_Format3__listOfEntityFilters),
	offsetof(struct E2SM_RC_ControlMessage_Format3__listOfEntityFilters, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfEntityFilters_2 = {
	"listOfEntityFilters",
	"listOfEntityFilters",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_listOfEntityFilters_tags_2,
	sizeof(asn_DEF_listOfEntityFilters_tags_2)
		/sizeof(asn_DEF_listOfEntityFilters_tags_2[0]) - 1, /* 1 */
	asn_DEF_listOfEntityFilters_tags_2,	/* Same as above */
	sizeof(asn_DEF_listOfEntityFilters_tags_2)
		/sizeof(asn_DEF_listOfEntityFilters_tags_2[0]), /* 2 */
	{ 0, &asn_PER_type_listOfEntityFilters_constr_2, SEQUENCE_OF_constraint },
	asn_MBR_listOfEntityFilters_2,
	1,	/* Single element */
	&asn_SPC_listOfEntityFilters_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_entityAgnosticControlRanP_List_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EntityAgnostic_ranP_ControlParameters,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_entityAgnosticControlRanP_List_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_entityAgnosticControlRanP_List_specs_4 = {
	sizeof(struct E2SM_RC_ControlMessage_Format3__entityAgnosticControlRanP_List),
	offsetof(struct E2SM_RC_ControlMessage_Format3__entityAgnosticControlRanP_List, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_entityAgnosticControlRanP_List_4 = {
	"entityAgnosticControlRanP-List",
	"entityAgnosticControlRanP-List",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_entityAgnosticControlRanP_List_tags_4,
	sizeof(asn_DEF_entityAgnosticControlRanP_List_tags_4)
		/sizeof(asn_DEF_entityAgnosticControlRanP_List_tags_4[0]) - 1, /* 1 */
	asn_DEF_entityAgnosticControlRanP_List_tags_4,	/* Same as above */
	sizeof(asn_DEF_entityAgnosticControlRanP_List_tags_4)
		/sizeof(asn_DEF_entityAgnosticControlRanP_List_tags_4[0]), /* 2 */
	{ 0, &asn_PER_type_entityAgnosticControlRanP_List_constr_4, SEQUENCE_OF_constraint },
	asn_MBR_entityAgnosticControlRanP_List_4,
	1,	/* Single element */
	&asn_SPC_entityAgnosticControlRanP_List_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2SM_RC_ControlMessage_Format3_1[] = {
	{ ATF_POINTER, 2, offsetof(struct E2SM_RC_ControlMessage_Format3, listOfEntityFilters),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_listOfEntityFilters_2,
		0,
		{ 0, &asn_PER_memb_listOfEntityFilters_constr_2,  memb_listOfEntityFilters_constraint_1 },
		0, 0, /* No default value */
		"listOfEntityFilters"
		},
	{ ATF_POINTER, 1, offsetof(struct E2SM_RC_ControlMessage_Format3, entityAgnosticControlRanP_List),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_entityAgnosticControlRanP_List_4,
		0,
		{ 0, &asn_PER_memb_entityAgnosticControlRanP_List_constr_4,  memb_entityAgnosticControlRanP_List_constraint_1 },
		0, 0, /* No default value */
		"entityAgnosticControlRanP-List"
		},
};
static const int asn_MAP_E2SM_RC_ControlMessage_Format3_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_E2SM_RC_ControlMessage_Format3_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E2SM_RC_ControlMessage_Format3_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* listOfEntityFilters */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* entityAgnosticControlRanP-List */
};
asn_SEQUENCE_specifics_t asn_SPC_E2SM_RC_ControlMessage_Format3_specs_1 = {
	sizeof(struct E2SM_RC_ControlMessage_Format3),
	offsetof(struct E2SM_RC_ControlMessage_Format3, _asn_ctx),
	asn_MAP_E2SM_RC_ControlMessage_Format3_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_E2SM_RC_ControlMessage_Format3_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E2SM_RC_ControlMessage_Format3 = {
	"E2SM-RC-ControlMessage-Format3",
	"E2SM-RC-ControlMessage-Format3",
	&asn_OP_SEQUENCE,
	asn_DEF_E2SM_RC_ControlMessage_Format3_tags_1,
	sizeof(asn_DEF_E2SM_RC_ControlMessage_Format3_tags_1)
		/sizeof(asn_DEF_E2SM_RC_ControlMessage_Format3_tags_1[0]), /* 1 */
	asn_DEF_E2SM_RC_ControlMessage_Format3_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2SM_RC_ControlMessage_Format3_tags_1)
		/sizeof(asn_DEF_E2SM_RC_ControlMessage_Format3_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E2SM_RC_ControlMessage_Format3_1,
	2,	/* Elements count */
	&asn_SPC_E2SM_RC_ControlMessage_Format3_specs_1	/* Additional specs */
};

