/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "defs/E2SM-RC-R003-v03.00.asn1"
 * 	`asn1c -fcompound-names -findirect-choice -fincludes-quoted -fno-include-deps -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_EntitySpecific_ranP_ControlParameters_H_
#define	_EntitySpecific_ranP_ControlParameters_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RANParameter-ID.h"
#include "RANParameter-ValueType.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EntitySpecific-ranP-ControlParameters */
typedef struct EntitySpecific_ranP_ControlParameters {
	RANParameter_ID_t	 ranParameter_ID;
	RANParameter_ValueType_t	 ranParameter_valueType;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EntitySpecific_ranP_ControlParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EntitySpecific_ranP_ControlParameters;
extern asn_SEQUENCE_specifics_t asn_SPC_EntitySpecific_ranP_ControlParameters_specs_1;
extern asn_TYPE_member_t asn_MBR_EntitySpecific_ranP_ControlParameters_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _EntitySpecific_ranP_ControlParameters_H_ */
#include "asn_internal.h"
