/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "defs/E2SM-RC-R003-v03.00.asn1"
 * 	`asn1c -fcompound-names -findirect-choice -fincludes-quoted -fno-include-deps -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_L2MACschChgType_Choice_H_
#define	_L2MACschChgType_Choice_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum L2MACschChgType_Choice_PR {
	L2MACschChgType_Choice_PR_NOTHING,	/* No components present */
	L2MACschChgType_Choice_PR_triggerType_Choice_MIMOandBFconfig
	/* Extensions may appear below */
	
} L2MACschChgType_Choice_PR;

/* Forward declarations */
struct TriggerType_Choice_MIMOandBFconfig;

/* L2MACschChgType-Choice */
typedef struct L2MACschChgType_Choice {
	L2MACschChgType_Choice_PR present;
	union L2MACschChgType_Choice_u {
		struct TriggerType_Choice_MIMOandBFconfig	*triggerType_Choice_MIMOandBFconfig;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} L2MACschChgType_Choice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_L2MACschChgType_Choice;
extern asn_CHOICE_specifics_t asn_SPC_L2MACschChgType_Choice_specs_1;
extern asn_TYPE_member_t asn_MBR_L2MACschChgType_Choice_1[1];
extern asn_per_constraints_t asn_PER_type_L2MACschChgType_Choice_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _L2MACschChgType_Choice_H_ */
#include "asn_internal.h"
