/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "defs/E2SM-RC-R003-v03.00.asn1"
 * 	`asn1c -fcompound-names -findirect-choice -fincludes-quoted -fno-include-deps -gen-PER -no-gen-OER -no-gen-example`
 */

#include "RANFunctionDefinition-Query-Item.h"

#include "Query-RANParameter-Item.h"
static int
memb_ran_QueryParameters_List_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 65535)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_ran_QueryParameters_List_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ran_QueryParameters_List_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ran_QueryParameters_List_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Query_RANParameter_Item,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ran_QueryParameters_List_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ran_QueryParameters_List_specs_7 = {
	sizeof(struct RANFunctionDefinition_Query_Item__ran_QueryParameters_List),
	offsetof(struct RANFunctionDefinition_Query_Item__ran_QueryParameters_List, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ran_QueryParameters_List_7 = {
	"ran-QueryParameters-List",
	"ran-QueryParameters-List",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ran_QueryParameters_List_tags_7,
	sizeof(asn_DEF_ran_QueryParameters_List_tags_7)
		/sizeof(asn_DEF_ran_QueryParameters_List_tags_7[0]) - 1, /* 1 */
	asn_DEF_ran_QueryParameters_List_tags_7,	/* Same as above */
	sizeof(asn_DEF_ran_QueryParameters_List_tags_7)
		/sizeof(asn_DEF_ran_QueryParameters_List_tags_7[0]), /* 2 */
	{ 0, &asn_PER_type_ran_QueryParameters_List_constr_7, SEQUENCE_OF_constraint },
	asn_MBR_ran_QueryParameters_List_7,
	1,	/* Single element */
	&asn_SPC_ran_QueryParameters_List_specs_7	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RANFunctionDefinition_Query_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Query_Item, ric_QueryStyle_Type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Style_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-QueryStyle-Type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Query_Item, ric_QueryStyle_Name),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Style_Name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-QueryStyle-Name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Query_Item, ric_QueryHeaderFormat_Type),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Format_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-QueryHeaderFormat-Type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Query_Item, ric_QueryDefinitionFormat_Type),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Format_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-QueryDefinitionFormat-Type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Query_Item, ric_QueryOutcomeFormat_Type),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Format_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-QueryOutcomeFormat-Type"
		},
	{ ATF_POINTER, 1, offsetof(struct RANFunctionDefinition_Query_Item, ran_QueryParameters_List),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_ran_QueryParameters_List_7,
		0,
		{ 0, &asn_PER_memb_ran_QueryParameters_List_constr_7,  memb_ran_QueryParameters_List_constraint_1 },
		0, 0, /* No default value */
		"ran-QueryParameters-List"
		},
};
static const int asn_MAP_RANFunctionDefinition_Query_Item_oms_1[] = { 5 };
static const ber_tlv_tag_t asn_DEF_RANFunctionDefinition_Query_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RANFunctionDefinition_Query_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ric-QueryStyle-Type */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ric-QueryStyle-Name */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ric-QueryHeaderFormat-Type */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ric-QueryDefinitionFormat-Type */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* ric-QueryOutcomeFormat-Type */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* ran-QueryParameters-List */
};
asn_SEQUENCE_specifics_t asn_SPC_RANFunctionDefinition_Query_Item_specs_1 = {
	sizeof(struct RANFunctionDefinition_Query_Item),
	offsetof(struct RANFunctionDefinition_Query_Item, _asn_ctx),
	asn_MAP_RANFunctionDefinition_Query_Item_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_RANFunctionDefinition_Query_Item_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	6,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RANFunctionDefinition_Query_Item = {
	"RANFunctionDefinition-Query-Item",
	"RANFunctionDefinition-Query-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_RANFunctionDefinition_Query_Item_tags_1,
	sizeof(asn_DEF_RANFunctionDefinition_Query_Item_tags_1)
		/sizeof(asn_DEF_RANFunctionDefinition_Query_Item_tags_1[0]), /* 1 */
	asn_DEF_RANFunctionDefinition_Query_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_RANFunctionDefinition_Query_Item_tags_1)
		/sizeof(asn_DEF_RANFunctionDefinition_Query_Item_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RANFunctionDefinition_Query_Item_1,
	6,	/* Elements count */
	&asn_SPC_RANFunctionDefinition_Query_Item_specs_1	/* Additional specs */
};

