/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "defs/E2SM-RC-R003-v03.00.asn1"
 * 	`asn1c -fcompound-names -findirect-choice -fincludes-quoted -fno-include-deps -gen-PER -no-gen-OER -no-gen-example`
 */

#include "TriggerType-Choice-L2MACschChg.h"

asn_TYPE_member_t asn_MBR_TriggerType_Choice_L2MACschChg_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TriggerType_Choice_L2MACschChg, l2MACschChgType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_L2MACschChgType_Choice,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"l2MACschChgType"
		},
};
static const ber_tlv_tag_t asn_DEF_TriggerType_Choice_L2MACschChg_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TriggerType_Choice_L2MACschChg_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* l2MACschChgType */
};
asn_SEQUENCE_specifics_t asn_SPC_TriggerType_Choice_L2MACschChg_specs_1 = {
	sizeof(struct TriggerType_Choice_L2MACschChg),
	offsetof(struct TriggerType_Choice_L2MACschChg, _asn_ctx),
	asn_MAP_TriggerType_Choice_L2MACschChg_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TriggerType_Choice_L2MACschChg = {
	"TriggerType-Choice-L2MACschChg",
	"TriggerType-Choice-L2MACschChg",
	&asn_OP_SEQUENCE,
	asn_DEF_TriggerType_Choice_L2MACschChg_tags_1,
	sizeof(asn_DEF_TriggerType_Choice_L2MACschChg_tags_1)
		/sizeof(asn_DEF_TriggerType_Choice_L2MACschChg_tags_1[0]), /* 1 */
	asn_DEF_TriggerType_Choice_L2MACschChg_tags_1,	/* Same as above */
	sizeof(asn_DEF_TriggerType_Choice_L2MACschChg_tags_1)
		/sizeof(asn_DEF_TriggerType_Choice_L2MACschChg_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_TriggerType_Choice_L2MACschChg_1,
	1,	/* Elements count */
	&asn_SPC_TriggerType_Choice_L2MACschChg_specs_1	/* Additional specs */
};

