/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "defs/E2SM-RC-R003-v03.00.asn1"
 * 	`asn1c -fcompound-names -findirect-choice -fincludes-quoted -fno-include-deps -gen-PER -no-gen-OER -no-gen-example`
 */

#include "TriggerType-Choice-MIMOandBFconfig.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_per_constraints_t asn_PER_type_mIMOtransModeState_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_mIMOtransModeState_value2enum_2[] = {
	{ 0,	7,	"enabled" },
	{ 1,	8,	"disabled" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_mIMOtransModeState_enum2value_2[] = {
	1,	/* disabled(1) */
	0	/* enabled(0) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_mIMOtransModeState_specs_2 = {
	asn_MAP_mIMOtransModeState_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_mIMOtransModeState_enum2value_2,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	3,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_mIMOtransModeState_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mIMOtransModeState_2 = {
	"mIMOtransModeState",
	"mIMOtransModeState",
	&asn_OP_NativeEnumerated,
	asn_DEF_mIMOtransModeState_tags_2,
	sizeof(asn_DEF_mIMOtransModeState_tags_2)
		/sizeof(asn_DEF_mIMOtransModeState_tags_2[0]) - 1, /* 1 */
	asn_DEF_mIMOtransModeState_tags_2,	/* Same as above */
	sizeof(asn_DEF_mIMOtransModeState_tags_2)
		/sizeof(asn_DEF_mIMOtransModeState_tags_2[0]), /* 2 */
	{ 0, &asn_PER_type_mIMOtransModeState_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_mIMOtransModeState_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_TriggerType_Choice_MIMOandBFconfig_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TriggerType_Choice_MIMOandBFconfig, mIMOtransModeState),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_mIMOtransModeState_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mIMOtransModeState"
		},
};
static const ber_tlv_tag_t asn_DEF_TriggerType_Choice_MIMOandBFconfig_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TriggerType_Choice_MIMOandBFconfig_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* mIMOtransModeState */
};
asn_SEQUENCE_specifics_t asn_SPC_TriggerType_Choice_MIMOandBFconfig_specs_1 = {
	sizeof(struct TriggerType_Choice_MIMOandBFconfig),
	offsetof(struct TriggerType_Choice_MIMOandBFconfig, _asn_ctx),
	asn_MAP_TriggerType_Choice_MIMOandBFconfig_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TriggerType_Choice_MIMOandBFconfig = {
	"TriggerType-Choice-MIMOandBFconfig",
	"TriggerType-Choice-MIMOandBFconfig",
	&asn_OP_SEQUENCE,
	asn_DEF_TriggerType_Choice_MIMOandBFconfig_tags_1,
	sizeof(asn_DEF_TriggerType_Choice_MIMOandBFconfig_tags_1)
		/sizeof(asn_DEF_TriggerType_Choice_MIMOandBFconfig_tags_1[0]), /* 1 */
	asn_DEF_TriggerType_Choice_MIMOandBFconfig_tags_1,	/* Same as above */
	sizeof(asn_DEF_TriggerType_Choice_MIMOandBFconfig_tags_1)
		/sizeof(asn_DEF_TriggerType_Choice_MIMOandBFconfig_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_TriggerType_Choice_MIMOandBFconfig_1,
	1,	/* Elements count */
	&asn_SPC_TriggerType_Choice_MIMOandBFconfig_specs_1	/* Additional specs */
};

