/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "defs/E2SM-RC-R003-v03.00.asn1"
 * 	`asn1c -fcompound-names -findirect-choice -fincludes-quoted -fno-include-deps -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_UE_Filter_ID_H_
#define	_UE_Filter_ID_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UE-Filter-ID */
typedef long	 UE_Filter_ID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_UE_Filter_ID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_UE_Filter_ID;
asn_struct_free_f UE_Filter_ID_free;
asn_struct_print_f UE_Filter_ID_print;
asn_constr_check_f UE_Filter_ID_constraint;
ber_type_decoder_f UE_Filter_ID_decode_ber;
der_type_encoder_f UE_Filter_ID_encode_der;
xer_type_decoder_f UE_Filter_ID_decode_xer;
xer_type_encoder_f UE_Filter_ID_encode_xer;
per_type_decoder_f UE_Filter_ID_decode_uper;
per_type_encoder_f UE_Filter_ID_encode_uper;
per_type_decoder_f UE_Filter_ID_decode_aper;
per_type_encoder_f UE_Filter_ID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _UE_Filter_ID_H_ */
#include "asn_internal.h"
