/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "defs/E2SM-RC-R003-v03.00.asn1"
 * 	`asn1c -fcompound-names -findirect-choice -fincludes-quoted -fno-include-deps -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_UEGroupDefinitionIdentifier_Item_H_
#define	_UEGroupDefinitionIdentifier_Item_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RANParameter-ID.h"
#include "RANParameter-ValueType.h"
#include "LogicalOR.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UEGroupDefinitionIdentifier-Item */
typedef struct UEGroupDefinitionIdentifier_Item {
	RANParameter_ID_t	 ranParameter_ID;
	RANParameter_ValueType_t	 ranParameter_valueType;
	LogicalOR_t	*logicalOR;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEGroupDefinitionIdentifier_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEGroupDefinitionIdentifier_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_UEGroupDefinitionIdentifier_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_UEGroupDefinitionIdentifier_Item_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _UEGroupDefinitionIdentifier_Item_H_ */
#include "asn_internal.h"
